const CHINESE_OF_WEEK: string[] = ['一', '二', '三', '四', '五', '六', '日'];
const YEAR: string = '年';
const MONTH: string = '月';
const DAY: string = '日';
const WEEK: string = '星期';
const DAYS_OF_WEEK: number = 7;
const SUNDAY_FIRST_SHIFT: number = 6;

export const weekTitleFunc = () => {
  const weekTitleArr = [];
  for (let index = 0;index < CHINESE_OF_WEEK.length; index++) {
    weekTitleArr.push(CHINESE_OF_WEEK[(index + SUNDAY_FIRST_SHIFT) % DAYS_OF_WEEK]); // Sunday is the first day
  }
  return weekTitleArr;
}

export const WEEK_TITLES: string[] = weekTitleFunc();

export function padTo2Digits(num: number) {
  return num.toString().padStart(2, '0');
}
export function dateFormat(date: Date) {
  return date.getFullYear() + YEAR + padTo2Digits(date.getMonth() + 1) + MONTH + padTo2Digits(date.getDate()) + DAY;
}

export function dateToStr(date: Date) {
  return date.toDateString();
}

export function weekDateFormat(timestamp: number) {
  let tempDate = new Date(timestamp);
  return dateFormat(tempDate) + WEEK + WEEK_TITLES[tempDate.getDay()];
}

export function sameDate(firstDate: Date, timestamp: number) {

  let secondDate = new Date(timestamp);
  if (firstDate.getFullYear() != secondDate.getFullYear()) {
    return false;
  }

  if (firstDate.getMonth() != secondDate.getMonth()) {
    return false;
  }

  if (firstDate.getDate() != secondDate.getDate()) {
    return false;
  }

  return true;
}

export function ratio2percent(ratio: number): string {
  return `${ratio * 100}%`;
}


export const frequencyRange = () => {
  const frequencyRangeArr = []
  CHINESE_OF_WEEK.forEach((item, index) => {
    frequencyRangeArr.push({
      id: (index + 1),
      label: `${WEEK}${item}`,
      isChecked: false
    })
  });
  return frequencyRangeArr;
}

export const oneWeekDictFunc = () => {
  const oneWeekDict = {};
  for (let index = 0;index < CHINESE_OF_WEEK.length; index++) {
    oneWeekDict[index + 1] = `${WEEK}${CHINESE_OF_WEEK[index]}`;
  }
  return oneWeekDict;
}
