server:
  port: 8000
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: business
          uri: http://localhost:8001/business
          predicates:
            - Path=/business/**