spring:
  datasource:
    url: jdbc:mysql://localhost:3306/payment-dev?serverTimezone=Asia/Shanghai
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
logging:
  level:
     com.ruyuan.payment.server.mapper: trace